/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * PreviewApi - axios parameter creator
 */
export const PreviewApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get box ID from signed preview URL token
         * @param {string} signedPreviewToken Signed preview URL token
         * @param {number} port Port number to get box ID from signed preview URL token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBoxIdFromSignedPreviewUrlToken: async (signedPreviewToken: string, port: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signedPreviewToken' is not null or undefined
            assertParamExists('getBoxIdFromSignedPreviewUrlToken', 'signedPreviewToken', signedPreviewToken)
            // verify required parameter 'port' is not null or undefined
            assertParamExists('getBoxIdFromSignedPreviewUrlToken', 'port', port)
            const localVarPath = `/preview/{signedPreviewToken}/{port}/box-id`
                .replace('{signedPreviewToken}', encodeURIComponent(String(signedPreviewToken)))
                .replace('{port}', encodeURIComponent(String(port)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Check if user has access to the box
         * @param {string} boxId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hasBoxAccess: async (boxId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'boxId' is not null or undefined
            assertParamExists('hasBoxAccess', 'boxId', boxId)
            const localVarPath = `/preview/{boxId}/access`
                .replace('{boxId}', encodeURIComponent(String(boxId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Check if box is public
         * @param {string} boxId ID of the box
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        isBoxPublic: async (boxId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'boxId' is not null or undefined
            assertParamExists('isBoxPublic', 'boxId', boxId)
            const localVarPath = `/preview/{boxId}/public`
                .replace('{boxId}', encodeURIComponent(String(boxId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Check if box auth token is valid
         * @param {string} boxId ID of the box
         * @param {string} authToken Auth token of the box
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        isValidAuthToken: async (boxId: string, authToken: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'boxId' is not null or undefined
            assertParamExists('isValidAuthToken', 'boxId', boxId)
            // verify required parameter 'authToken' is not null or undefined
            assertParamExists('isValidAuthToken', 'authToken', authToken)
            const localVarPath = `/preview/{boxId}/validate/{authToken}`
                .replace('{boxId}', encodeURIComponent(String(boxId)))
                .replace('{authToken}', encodeURIComponent(String(authToken)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PreviewApi - functional programming interface
 */
export const PreviewApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PreviewApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get box ID from signed preview URL token
         * @param {string} signedPreviewToken Signed preview URL token
         * @param {number} port Port number to get box ID from signed preview URL token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBoxIdFromSignedPreviewUrlToken(signedPreviewToken: string, port: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBoxIdFromSignedPreviewUrlToken(signedPreviewToken, port, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PreviewApi.getBoxIdFromSignedPreviewUrlToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Check if user has access to the box
         * @param {string} boxId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hasBoxAccess(boxId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hasBoxAccess(boxId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PreviewApi.hasBoxAccess']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Check if box is public
         * @param {string} boxId ID of the box
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async isBoxPublic(boxId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.isBoxPublic(boxId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PreviewApi.isBoxPublic']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Check if box auth token is valid
         * @param {string} boxId ID of the box
         * @param {string} authToken Auth token of the box
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async isValidAuthToken(boxId: string, authToken: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.isValidAuthToken(boxId, authToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PreviewApi.isValidAuthToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PreviewApi - factory interface
 */
export const PreviewApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PreviewApiFp(configuration)
    return {
        /**
         * 
         * @summary Get box ID from signed preview URL token
         * @param {string} signedPreviewToken Signed preview URL token
         * @param {number} port Port number to get box ID from signed preview URL token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBoxIdFromSignedPreviewUrlToken(signedPreviewToken: string, port: number, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.getBoxIdFromSignedPreviewUrlToken(signedPreviewToken, port, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Check if user has access to the box
         * @param {string} boxId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hasBoxAccess(boxId: string, options?: RawAxiosRequestConfig): AxiosPromise<boolean> {
            return localVarFp.hasBoxAccess(boxId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Check if box is public
         * @param {string} boxId ID of the box
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        isBoxPublic(boxId: string, options?: RawAxiosRequestConfig): AxiosPromise<boolean> {
            return localVarFp.isBoxPublic(boxId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Check if box auth token is valid
         * @param {string} boxId ID of the box
         * @param {string} authToken Auth token of the box
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        isValidAuthToken(boxId: string, authToken: string, options?: RawAxiosRequestConfig): AxiosPromise<boolean> {
            return localVarFp.isValidAuthToken(boxId, authToken, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PreviewApi - object-oriented interface
 */
export class PreviewApi extends BaseAPI {
    /**
     * 
     * @summary Get box ID from signed preview URL token
     * @param {string} signedPreviewToken Signed preview URL token
     * @param {number} port Port number to get box ID from signed preview URL token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getBoxIdFromSignedPreviewUrlToken(signedPreviewToken: string, port: number, options?: RawAxiosRequestConfig) {
        return PreviewApiFp(this.configuration).getBoxIdFromSignedPreviewUrlToken(signedPreviewToken, port, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Check if user has access to the box
     * @param {string} boxId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public hasBoxAccess(boxId: string, options?: RawAxiosRequestConfig) {
        return PreviewApiFp(this.configuration).hasBoxAccess(boxId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Check if box is public
     * @param {string} boxId ID of the box
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public isBoxPublic(boxId: string, options?: RawAxiosRequestConfig) {
        return PreviewApiFp(this.configuration).isBoxPublic(boxId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Check if box auth token is valid
     * @param {string} boxId ID of the box
     * @param {string} authToken Auth token of the box
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public isValidAuthToken(boxId: string, authToken: string, options?: RawAxiosRequestConfig) {
        return PreviewApiFp(this.configuration).isValidAuthToken(boxId, authToken, options).then((request) => request(this.axios, this.basePath));
    }
}

