/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface BoxInfo {
    /**
     * The creation timestamp of the project
     */
    'created': string;
    /**
     * Deprecated: The name of the box
     * @deprecated
     */
    'name': string;
    /**
     * Additional metadata provided by the provider
     */
    'providerMetadata'?: string;
}

