/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The state of the box
 */

export const BoxState = {
    CREATING: 'creating',
    RESTORING: 'restoring',
    DESTROYED: 'destroyed',
    DESTROYING: 'destroying',
    STARTED: 'started',
    STOPPED: 'stopped',
    STARTING: 'starting',
    STOPPING: 'stopping',
    ERROR: 'error',
    BUILD_FAILED: 'build_failed',
    PENDING_BUILD: 'pending_build',
    BUILDING_SNAPSHOT: 'building_snapshot',
    UNKNOWN: 'unknown',
    PULLING_SNAPSHOT: 'pulling_snapshot',
    ARCHIVED: 'archived',
    ARCHIVING: 'archiving',
    RESIZING: 'resizing',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type BoxState = typeof BoxState[keyof typeof BoxState];



