/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateDockerRegistry {
    /**
     * Registry name
     */
    'name': string;
    /**
     * Registry URL
     */
    'url': string;
    /**
     * Registry username
     */
    'username': string;
    /**
     * Registry password
     */
    'password': string;
    /**
     * Registry project
     */
    'project'?: string;
    /**
     * Registry type
     */
    'registryType': CreateDockerRegistryRegistryTypeEnum;
    /**
     * Set as default registry
     */
    'isDefault'?: boolean;
}

export const CreateDockerRegistryRegistryTypeEnum = {
    INTERNAL: 'internal',
    ORGANIZATION: 'organization',
    TRANSIENT: 'transient',
    BACKUP: 'backup',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type CreateDockerRegistryRegistryTypeEnum = typeof CreateDockerRegistryRegistryTypeEnum[keyof typeof CreateDockerRegistryRegistryTypeEnum];


