/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The type of the job
 */

export const JobType = {
    CREATE_BOX: 'CREATE_BOX',
    START_BOX: 'START_BOX',
    STOP_BOX: 'STOP_BOX',
    DESTROY_BOX: 'DESTROY_BOX',
    RESIZE_BOX: 'RESIZE_BOX',
    CREATE_BACKUP: 'CREATE_BACKUP',
    BUILD_SNAPSHOT: 'BUILD_SNAPSHOT',
    PULL_SNAPSHOT: 'PULL_SNAPSHOT',
    RECOVER_BOX: 'RECOVER_BOX',
    INSPECT_SNAPSHOT_IN_REGISTRY: 'INSPECT_SNAPSHOT_IN_REGISTRY',
    REMOVE_SNAPSHOT: 'REMOVE_SNAPSHOT',
    UPDATE_BOX_NETWORK_SETTINGS: 'UPDATE_BOX_NETWORK_SETTINGS',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type JobType = typeof JobType[keyof typeof JobType];



