/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SignedPortPreviewUrl {
    /**
     * ID of the box
     */
    'boxId': string;
    /**
     * Port number of the signed preview URL
     */
    'port': number;
    /**
     * Token of the signed preview URL
     */
    'token': string;
    /**
     * Signed preview url
     */
    'url': string;
}

