/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SshAccessDto {
    /**
     * Unique identifier for the SSH access
     */
    'id': string;
    /**
     * ID of the box this SSH access is for
     */
    'boxId': string;
    /**
     * SSH access token
     */
    'token': string;
    /**
     * When the SSH access expires
     */
    'expiresAt': Date;
    /**
     * When the SSH access was created
     */
    'createdAt': Date;
    /**
     * When the SSH access was last updated
     */
    'updatedAt': Date;
    /**
     * SSH command to connect to the box
     */
    'sshCommand': string;
}

