/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The type of event being sent
 */

export const WebhookEvent = {
    BOX_CREATED: 'box.created',
    BOX_STATE_UPDATED: 'box.state.updated',
    SNAPSHOT_CREATED: 'snapshot.created',
    SNAPSHOT_STATE_UPDATED: 'snapshot.state.updated',
    SNAPSHOT_REMOVED: 'snapshot.removed',
    VOLUME_CREATED: 'volume.created',
    VOLUME_STATE_UPDATED: 'volume.state.updated',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type WebhookEvent = typeof WebhookEvent[keyof typeof WebhookEvent];



