# TODO: maybe remove musl_v1_2_3 after upgrade libkrun?
# ref https://github.com/libkrun/libkrun/pull/663
[target.'cfg(target_env = "musl")']
rustflags = ["--cfg", "musl_v1_2_3", "-C", "link-arg=-Wl,-z,stack-size=2097152"]
