PHONY_TARGETS += help

help:
	@echo "BoxLite Build Commands:"
	@echo ""
	@echo "  Setup:"
	@echo "    make setup          - Dev setup (same as make setup:dev)"
	@echo "    make setup:build    - Build-only deps (recommended for CI)"
	@echo "    make setup:test     - Test/dev extras (nextest, node deps, hooks, python venv)"
	@echo "    make setup:dev      - setup:build + setup:test"
	@echo ""
	@echo "  Cleanup:"
	@echo "    make clean          - Clean everything (cargo, SDKs, .venv, temp files)"
	@echo "    make clean:dist     - Clean only SDK distribution artifacts"
	@echo ""
	@echo "  Code Quality:"
	@echo "    make fmt                   - Format Rust/Python/Node/C code"
	@echo "    make fmt:check             - Check formatting for Rust/Python/Node/C"
	@echo "    make lint                  - Run lint checks (Rust/Python/Node/C)"
	@echo "    make lint:fix              - Auto-fix via formatters + Python lint fixes, then re-check"
	@echo "    make clippy                - Run Rust clippy checks (includes macOS cross-target guest)"
	@echo "    make lint:apps             - Lint the apps workspace TypeScript (eslint)"
	@echo ""
	@echo "  Build:"
	@echo "    make cli            - Build the CLI (release by default; BUILD_PROFILE=debug for debug)"
	@echo "    make guest          - Build the guest binary (cross-compile for VM)"
	@echo "    make runtime        - Build runtime artifacts (release by default; BUILD_PROFILE=debug for debug)"
	@echo "    make skillbox-image - Build SkillBox Docker image (APT_SOURCE=mirrors.aliyun.com for China)"
	@echo "    make build:apps     - Build the apps workspace (api, dashboard, runner, libs…)"
	@echo ""
	@echo "  Testing (strict full-matrix default):"
	@echo "    make test                   - Run full test matrix (same as make test:all)"
	@echo "    make test:all               - Run full test matrix (unit + integration)"
	@echo "    make test:unit              - Run all unit suites"
	@echo "    make test:integration       - Run all integration suites"
	@echo "    make test:unit:core         - Run Rust/FFI unit suites"
	@echo "    make test:integration:core  - Run core integration suites (Rust + CLI)"
	@echo "    make test:unit:sdk          - Run SDK unit suites (Python + Node + C + Go)"
	@echo "    make test:integration:sdk   - Run SDK integration suites (Python + Node + C)"
	@echo "    make test:unit:rust         - Run Rust unit tests (nextest when available)"
	@echo "    make test:warm-cache:rust   - Pre-warm Rust integration image cache"
	@echo "    make test:integration:rust  - Run Rust integration tests (requires VM, FILTER=<pattern>)"
	@echo "    make test:unit:ffi          - Run BoxLite FFI unit tests"
	@echo "    make test:integration:cli   - Run CLI integration tests (FILTER=<pattern>)"
	@echo "    make test:unit:python       - Run Python SDK unit tests"
	@echo "    make test:integration:python - Run Python SDK integration tests"
	@echo "    make test:all:python        - Run Python SDK unit + integration tests"
	@echo "    make test:unit:node         - Run Node.js SDK unit tests"
	@echo "    make test:integration:node  - Run Node.js SDK integration tests (requires VM)"
	@echo "    make test:all:node          - Run all Node.js SDK tests"
	@echo "    make test:unit:go           - Run Go SDK unit tests"
	@echo "    make test:all:go            - Run all Go SDK tests"
	@echo "    make test:unit:c            - Run C SDK unit tests (no VM required)"
	@echo "    make test:integration:c     - Run C SDK integration tests (requires VM)"
	@echo "    make test:all:c             - Run C SDK full suite (unit + integration)"
	@echo "    make test:apps              - Run the apps workspace test matrix"
	@echo "    make test:e2e:setup         - Bootstrap local stack (PG/Redis/Registry/API/Runner) + fixture data; idempotent"
	@echo "    make test:e2e               - Run E2E suite (SDK→API→Runner→VM); see scripts/test/e2e/README.md"
	@echo "    make test:e2e:two-sided     - PR_REF=<branch> required; proves test catches bug + PR fixes it"
	@echo "    make test:stress:api-read   - Run read-only k6 stress test against a deployed REST API"
	@echo "    make test:stress:api-read-local - Run low-rate local-network API stress canary"
	@echo "    make test:stress:api-create-box - Run k6 stress test that creates and deletes boxes"
	@echo "    make test:stress:api-create-box-local - Run low-rate local-network box creation canary"
	@echo "    make test:stress:api-vm-lifecycle - Run k6 stress test that holds real VMs concurrently"
	@echo "    make test:stress:api-vm-lifecycle-local - Run low-rate local-network VM lifecycle canary"
	@echo ""
	@echo "  Coverage:"
	@echo "    make coverage              - Generate HTML coverage report (unit tests)"
	@echo "    make coverage:lcov         - Generate LCOV output for CI upload"
	@echo "    make coverage:integration  - Generate coverage for Rust integration tests"
	@echo ""
	@echo "  Local Development:"
	@echo "    make dev:python     - Build and install Python SDK locally (debug mode)"
	@echo "    make dev:c          - Build C SDK locally (debug mode)"
	@echo "    make dev:node       - Build and link Node.js SDK locally (debug mode)"
	@echo "    make dev:go         - Build Go SDK locally (debug mode)"
	@echo ""
	@echo "  Distribution:"
	@echo "    make dist:python    - Build portable wheel with cibuildwheel"
	@echo "    make dist:c         - Build C SDK release and stage to sdks/c/dist/"
	@echo "    make dist:node      - Build npm package with napi-rs"
	@echo "    make dist:go        - Build Go SDK release"
	@echo ""
	@echo "Platform: $$(uname) ($$(uname -m))"
	@echo ""
